config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :rentals
    end
  end

  root to: "pages#home"

  resources :rentals

  delete "rentals/:id", to: "rentals#destroy", as: :destroy_rental

  resources :painels, only: [:index]
end

app/models/address.rb
class Address < ApplicationRecord
  validates :street, presence: true
  validates :number, presence: true
  validates :neighborhood, presence: true
  validates :city, presence: true
  validates :country, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/painel.rb
class Painel < ApplicationRecord
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :address

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/api/v1/rentals_controller.rb
class Api::V1::RentalsController < Api::V1::BaseController
  before_action :set_rental, only: [:show, :update]

  def index
    @rentals = policy_scope(Rental)
    authorize @rentals
  end

  def update
    if @rental.update(rental_params)
      render :show
    else
      render_error
    end
  end

  private

  def rental_params
    params.require(:rental).permit(
      :title, :price, :bathroom, :bedroom, :garage,
      :address_id, :main_photo, :squareft, :photo_one, :photo_two, :photo_three
    )
  end

  def set_rental
    @rental = Rental.find(params[:id])
    authorize @rental
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

   private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @rentals = Rental.all
  end

  private


end

app/controllers/painels_controller.rb
class PainelsController < ApplicationController
  def index
    @painels = policy_scope(Painel)
    @rentals = Rental.all
    authorize @painels
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,  :home, :show]
  before_action :set_rental, except: [:index, :create]

  def index
    @rentals = policy_scope(Rental)
    authorize @rentals
  end

  def show
    authorize @rental
  end

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    set_user
    @rental = Rental.new(rentals_params)
    @rental.user = current_user
    authorize @rental

    if @rental.save
      redirect_to painels_path
    else
      render :new
    end
  end

  def edit
    authorize @rental
  end

  def update
    if @rental.update(rentals_params)
      redirect_to painels_path(@painel)
      authorize @rental
    else
      render :new
      authorize @rental
    end
  end

  def destroy
    @rental.destroy
    authorize @rental

    redirect_to painels_path
  end

  private

  def rentals_params
    params.require(:rental).permit(
      :title,
      :price,
      :bathroom,
      :bedroom,
      :garage,
      :address_id,
      :main_photo,
      :squareft,
      :photo_one,
      :photo_two,
      :photo_three,
      :content
    )
  end

  def set_user
    @user = current_user.id
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/painels_helper.rb
module PainelsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealStateRailsApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;700&display=swap" rel="stylesheet">

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/d45b7ae9b8.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>


    <!-- JS bundle Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_bannerContent.html.erb
<div class="banner-content">
  <div class="container">
    <h1 class="banner-title">As melhores casas do mercado</h1>
    <h3 class="banner-subtitle">Pesquise agora por endereço</h3>
  </div>
</div>

app/views/pages/_footer.html.erb
<footer>
  <div class="footer-content">
    <p class="footer-text mt-3">Desenvolvido por: Thiago H. R. Costa - 2021 - Confira meu <a href="https://github.com/thiagohrcosta" target="_blank"><i class="fab fa-github"></i></a> </p>
  </div>
</footer>

app/views/pages/_navbar.html.erb
<div class="container pt-5">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><%= image_tag "https://res.cloudinary.com/dloadb2bx/image/upload/v1622689257/logoHouse_u0zl9l.png", class: "logo-img"%> Real State - API</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "Para alugar", rentals_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Acessar API", "/api/v1/rentals", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <% if user_signed_in? %>
                  <%= link_to "Dashboard",  painels_path, class: "btn btn-custom-login btn-outline-primary" %>
                <% else %>
                  <%= link_to "Login",  new_user_registration_path, class: "btn btn-custom-login btn-outline-primary" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

app/views/pages/_search.html.erb
<div class="container">
  <div class="search-bg">
    <input class="input-search" type="text">
    <span class="btn btn-search">Encontrar</span>
  </div>
</div>

app/views/pages/home.html.erb
<div class="bg-header">

  <div class="navbar-custom">
    <%= render 'navbar' %>
    <%= render 'bannerContent' %>
    <%= render 'search' %>
  </div>
</div>

<div class="container">
  <div class="rental-grid">
    <% @rentals.sample(6).each do |rental| %>
      <div class="rental-card">
        <%= link_to rental_path(rental.id), class: "rental-link" do %>
        <img class="card-photo" src="<%= rental.main_photo %>" alt="">
        <p class="card-title"><%= rental.title %></p>

        <p class="card-address"><%= rental.address.street %>, <%= rental.address.number %>, <%= rental.address.city %></p>

        <div class="card-icons">
          <div class="icons-container">
            <div>
            <i class="fas fa-shower fa-lg"></i><span class="icon-value"> <%= rental.bathroom %></span>
            </div>
            <div>
              <i class="fas fa-bed fa-lg"></i><span class="icon-value"> <%= rental.bedroom %></span>
            </div>
            <div>
              <i class="fas fa-car fa-lg"></i><span class="icon-value"> <%= rental.garage %></span>
            </div>
            <div>
              <i class="fas fa-vector-square fa-lg"></i><span class="icon-value"> <%= rental.squareft %></span>
            </div>
          </div>
          <div class="">
            <p class="rent-value">R$ <%= rental.price %>0</p>
          </div>
        </div>
    <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'footer' %>

app/views/painels/index.html.erb
<div class="bg-header">

    <%= render './pages/navbar' %>
    <div class="container">

      <div class="painel-control">
        <div class="admin-header mb-5">
          <h3>Gerenciar imóveis</h3>
          <%= link_to "Cadastrar imóvel", new_rental_path, class: "btn-new-home" %>
        </div>

        <div class="rental-admin-container">
          <% @rentals.each do |rental| %>
          <% if rental.user_id == current_user.id %>
            <div class="rental-admin-flex mb-3">
              <div class="row">
                <div class="col-lg-3">
                  <img class="w-100" src="<%= rental.main_photo %>" alt="">
                </div>
                <div class="col-lg-7">
                  <h2><%= rental.title %></h2>
                  <p><%= rental.address.street %>, <%= rental.address.number %>, <%= rental.address.neighborhood %>, <%= rental.address.city %></p>

                </div>
                <div class="col-lg-2">

                    <%= link_to "Editar", edit_rental_path(rental.id), class: "btn btn-admin-edit w-100" %>


                    <%= link_to "Apagar", destroy_rental_path(rental.id),  method: :delete, data: { confirm: "Tem certeza que deseja remover?"}, class: "btn btn-admin-delete w-100 mt-3" %>

                </div>
              </div>
            </div>
          <% else %>
            <div class="blank-admin"></div>
          <% end %>

          <% end %>
        </div>
      </div>

    </div>
<%= render './pages/footer' %>
</div>

app/views/rentals/_content.html.erb
<div class="show-gird">
  <% @rentals.shuffle.each do |rental| %>
    <div class="show-house-card">
      <div class="row">
        <div class="col-lg-3">
          <img class="img-index-rentals" src="<%= rental.main_photo %>" alt="">

        </div>
        <div class="col-lg-9">
          <div class="rental-details-flex">
            <h3><%= rental.title %></h3>
            <%= link_to "Ver detalhes", rental_path(rental.id), class: "btn-see-detail" %>
          </div>
          <p><%= rental.address.street%>, <%= rental.address.number %>, <%= rental.address.neighborhood %>, <%= rental.address.city %></p>
           <div class="icons-container mt-3 mb-3">
              <div>
              <i class="fas fa-shower fa-lg"></i><span class="icon-value"> <%= rental.bathroom %></span>
              </div>
              <div>
                <i class="fas fa-bed fa-lg"></i><span class="icon-value"> <%= rental.bedroom %></span>
              </div>
              <div>
                <i class="fas fa-car fa-lg"></i><span class="icon-value"> <%= rental.garage %></span>
              </div>
              <div>
                <i class="fas fa-vector-square fa-lg"></i><span class="icon-value"> <%= rental.squareft %>m²</span>
            </div>
        </div>
      </div>


    </div>
    <hr>
  <% end %>

</div>
</div>

app/views/rentals/_form.html.erb
<%= simple_form_for @rental do |f| %>
  <%= f.input :title, label: "Título" %>
  <%= f.input :price, label: "Valor do aluguel" %>
  <%= f.association :address, label: "Endereço cadastrado" %>
  <%= f.input :main_photo, label: "Foto principal" %>
  <%= f.input :photo_one, label: "Foto para slide 1" %>
  <%= f.input :photo_two, label: "Foto para slide 2" %>
  <%= f.input :photo_three, label: "Foto para slide 3" %>
  <%= f.input :squareft, label: "Metros quadrados" %>
  <%= f.input :bathroom, label: "Banheiros" %>
  <%= f.input :bedroom, label: "Quartos" %>
  <%= f.input :garage, label: "Vagas de garagem" %>
  <%= f.input :content, label: "Descrição do imóvel" %>

  <%= f.submit "Cadastrar", class: "btn btn-create w-100" %>



<% end %>

app/views/rentals/_sidebar.html.erb
<div class="form-custom">
  <h3 class="text-center text-white mb-3">O que buscar?</h3>
  <select class="form-select mt-3 mb-3" aria-label="Default select example">
    <option selected>Qual bairro?</option>
    <option value="1">Centro</option>
    <option value="2">Barro Preto</option>
  </select>
  <select class="form-select mt-3 mb-3" aria-label="Default select example">
    <option selected>Quantos banheiros?</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="2">3</option>
  </select>
  <select class="form-select mt-3 mb-3" aria-label="Default select example">
    <option selected>Quantos quartos?</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="2">3</option>
  </select>


  <label for="customRange1" class="form-label text-white">Valor do aluguel</label>
  <input type="range" class="form-range" id="customRange1">

  <span class="btn btn-search-rentals w-100">Buscar</span>
</div>

app/views/rentals/edit.html.erb
<div class="bg-header">
  <%= render './pages/navbar' %>
    <div class="container">
      <div class="new-form-container">
          <%= render 'form', rental: @rental %>
      </div>
    </div>

  <%= render './pages/footer' %>
</div>

app/views/rentals/index.html.erb
<div class="bg-header">

<%= render './pages/navbar' %>

<div class="container mt-5">
  <div class="container-rentals">
    <div class="row">
      <div class="col-lg-3">
        <%= render 'sidebar' %>
      </div>
      <div class="col-lg-9">
        <%= render 'content' %>
    </div>
  </div>

</div>
</div>

app/views/rentals/new.html.erb
<div class="bg-header">
  <%= render './pages/navbar' %>
    <div class="container">
      <div class="new-form-container">
          <%= render 'form', rental: @rental %>
      </div>
    </div>

  <%= render './pages/footer' %>
</div>

app/views/rentals/show.html.erb
<div
  class="show-header"
  style="background-image: linear-gradient( rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6) ), url(<%= @rental.main_photo %>);">


  <div class="navbar-custom">
    <%= render 'pages/navbar' %>
    <div class="text-center">
        <h1 class="show-header-title"><%= @rental.title %> </h1>

        <h4 class="address-show"><%= @rental.address.street %>, <%= @rental.address.number %>, <%= @rental.address.city %></h4>

    </div>

  </div>
</div>

<div class="container">
  <div class="show-content">
    <div class="row">
      <div class="col-lg-6">
          <div class="icons-container mt-3 mb-3">
            <div>
            <i class="fas fa-shower fa-lg"></i><span class="icon-value"> <%= @rental.bathroom %></span>
            </div>
            <div>
              <i class="fas fa-bed fa-lg"></i><span class="icon-value"> <%= @rental.bedroom %></span>
            </div>
            <div>
              <i class="fas fa-car fa-lg"></i><span class="icon-value"> <%= @rental.garage %></span>
            </div>
            <div>
              <i class="fas fa-vector-square fa-lg"></i><span class="icon-value"> <%= @rental.squareft %>m²</span>
            </div>
          </div>
        <p><%= @rental.content %></p>
      </div>
      <div class="col-lg-6">
        <div class="carousel-inner">

          <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="<%= @rental.photo_one %>" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="<%= @rental.photo_two %>" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="<%= @rental.photo_three %>" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>

        </div>
      </div>
    </div>
  </div>

</div>